// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'Alegny_provider';
  static const String PROJECT_VERSION = '0.0.0+1';
  static const String APK_ICON = 'assets/images/apk_icon.png';
}
