// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String PROJECT_NAME = 'Alegny_provider';
  static const String PROJECT_VERSION = '0.0.0+1';
  static const String INTER_28PT_BOLD = 'Inter_28pt-Bold';
  static const String INTER_28PT_LIGHT = 'Inter_28pt-Light';
  static const String INTER_28PT_MEDIUM = 'Inter_28pt-Medium';
  static const String INTER_28PT_REGULAR = 'Inter_28pt-Regular';
}
